### ISSUE TITLE
Git fails on merge of remote submodule with `stderr: merge: main - not something we can merge`

### ISSUE THREAD

**Issue by langfield** [langfield/ki#67]
This happened because the relevant branch name in the added submodule (`langfield/karelze-anki-decks.git`) was not be equal to the `ki` constant `BRANCH_NAME == "main"`. The default branch in the submodule was `master`.

A test can easily be written for this.

See below.

```python
(anki) user@computer:~/karelze-push$ ki pull
Pulling from /home/user/.local/share/Anki2/karelze-push/collection.anki2
Computed md5sum: 569ee235326e84108704fdb54618a1e2
Found .anki2 file at /home/user/.local/share/Anki2/karelze-push/collection.anki2
Computed md5sum: 569ee235326e84108704fdb54618a1e2
Cloning into /tmp/tmpld6db4qm/ki-remote/569ee235326e84108704fdb54618a1e2...
Notes: 100%|██████████████████████████████| 6400/6400 [00:01<00:00, 4841.79it/s]
HTML: 100%|█████████████████████████████████████| 32/32 [00:00<00:00, 52.14it/s]
Media: 100%|█████████████████████████████| 6400/6400 [00:00<00:00, 11976.77it/s]
Decks:  53%|██████████████████▉                 | 20/38 [00:00<00:00, 34.34it/s]2022-08-22 09:46:52.653 | WARNING  | ki:get_note_path:727 - Slug for 1661106351317 is empty. Using nid as filename
Decks: 100%|████████████████████████████████████| 38/38 [00:01<00:00, 32.08it/s]
Warnings suppressed: 60 (show with --verbose)
Wrote md5sum to /tmp/tmpld6db4qm/ki-remote/569ee235326e84108704fdb54618a1e2/.ki/hashes
Patches: 100%|███████████████████████████| 10613/10613 [00:32<00:00, 321.81it/s]
Applied 1 patches within submodules.
  Patched karelze-anki-decks
Traceback (most recent call last):
  File "/home/user/conda/envs/anki/bin/ki", line 33, in <module>
    sys.exit(load_entry_point(ki, console_scripts, ki)())
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "<@beartype(ki.pull) at 0x7f224f2e0ca0>", line 10, in pull
  File "/home/user/pkgs/ki/ki/__init__.py", line 1855, in pull
    _pull(kirepo, silent=False)
  File "<@beartype(ki._pull) at 0x7f224f2e0b80>", line 49, in _pull
  File "/home/user/pkgs/ki/ki/__init__.py", line 2096, in _pull
    remote_sm.git.merge(["-s", "ours", BRANCH_NAME])
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd(git) failed due to: exit code(1)
  cmdline: git merge -s ours main
  stderr: merge: main - not something we can merge
```

**Comment by langfield** [comment]
Fixed by #68.
