### ISSUE TITLE
`Unexpected token Token('ANKINAME', 'guid')` on seemingly valid note file

### ISSUE THREAD

**Issue by langfield** [langfield/ki#75]
This happened during normal usage towards the end of a `ki push`. The following script was written to reproduce the error.

```python
from pathlib import Path
from lark import Lark
import ki
from ki.transformer import NoteTransformer
grammar_path = Path(ki.__file__).resolve().parent / "grammar.lark"
grammar = grammar_path.read_text(encoding="UTF-8")
parser = Lark(grammar, start="note", parser="lalr")
transformer = NoteTransformer()
note: str = (Path.home() / "10016.md").resolve().read_text(encoding="UTF-8")
tree = parser.parse(note)
out = transformer.transform(tree)
print(out)
```

The error:
```python
(anki) user@computer:~$ python3 parse.py 
    
Traceback (most recent call last):
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/lexer.py", line 528, in lex 
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches 'g' in the current parser context, at line 3 col 1

guid: e&b23Z6:Bx
^
Expected one of: 
        * GUID

Previous tokens: Token('TRIPLEBACKTICKS', '```\n')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/parse.py", line 10, in <module>
    tree = parser.parse(note)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/lark/lexer.py", line 537, in lex 
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('ANKINAME', 'guid') at line 3, column 1.
Expected one of: 
        * GUID
Previous tokens: [Token('TRIPLEBACKTICKS', '```\n')]
```

The offending note file:
````markdown
# Note
```
guid: e&b23Z6:Bx
notetype: Basic
```

### Tags
```
```

## Front
100*16

## Back
1600
````

**Comment by langfield** [comment]
This appears to be because Anki `guid`s are allowed to contain colons, but the `grammar.lark` file uses `ANKICHAR`s for this, which does not allow the colon.
