### ISSUE TITLE
Failed Clone on Windows (OSError: Invalid argument for path that contains asterisk)

### ISSUE THREAD

**Issue by pwintz** [langfield/ki#87]
When I clone on Windows, I am seeing the following error:

```
Cloning into 'C:\Users\pwintz\flashcards\ki\collection'...
Notes: 100%|##############################| 3607/3607 [00:02<00:00, 1686.82it/s]
HTML: 100%|#####################################| 11/11 [00:01<00:00,  7.55it/s]
Media: 100%|#############################| 3607/3607 [00:00<00:00, 23412.28it/s]
Decks:  12%|####3                               | 11/90 [00:00<00:03, 20.10it/s]2022-09-09 22:56:00.489 | WARNING  | ki:get_note_path:853 - Slug for 'QM6kTt.Nt*' is empty. Using guid as filename
Decks:  13%|####8                               | 12/90 [00:00<00:04, 17.77it/s]
Traceback (most recent call last):
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\Scripts\ki-script.py", line 33, in <module>
    sys.exit(load_entry_point('ki==0.0.4a0', 'console_scripts', 'ki')())
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1993, in clone
    raise err
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1979, in clone
    _, _ = _clone(
  File "<@beartype(ki._clone) at 0x22bd2204430>", line 104, in _clone
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 2052, in _clone
    latent_links: Set[LatentSymlink] = write_repository(
  File "<@beartype(ki.write_repository) at 0x22bd21f9e50>", line 123, in write_repository
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1270, in write_repository
    latent_links: Set[LatentSymlink] = write_decks(
  File "<@beartype(ki.write_decks) at 0x22bd21f9f70>", line 121, in write_decks
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1379, in write_decks
    node_cids, node_notes, node_latent_links = write_deck_node_cards(
  File "<@beartype(ki.write_deck_node_cards) at 0x22bd21ff0d0>", line 158, in write_deck_node_cards
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1469, in write_deck_node_cards
    note_path: ExtantFile = F.write(note_path, payload)
  File "<@beartype(ki.functional.write) at 0x22bd21c3820>", line 52, in write
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\functional.py", line 164, in write
    with open(path, "w+", encoding="UTF-8") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\pwintz\\flashcards\\ki\\collection\\Life\\Countries\\QM6kTt.Nt*.md'

```
My guess is that the asterisk in the file name is causing problems.

**Comment by pwintz** [comment]
Here is the contents of the Markdown file that Ki is trying to write:

```
# Note
```
guid: QM6kTt.Nt*
notetype: Image Occlusion Enhanced
```

### Tags
```
```

## ID (hidden)
8d46fbb2bee941a5b0bfe25b9284d27e-ao-28

## Header


## Image
<img src="tmps727ndlh.png">

## Question Mask
<img src="8d46fbb2bee941a5b0bfe25b9284d27e-ao-28-Q.svg">

## Footer


## Remarks


## Sources


## Extra 1


## Extra 2


## Answer Mask
<img src="8d46fbb2bee941a5b0bfe25b9284d27e-ao-28-A.svg">

## Original Mask
<img src="8d46fbb2bee941a5b0bfe25b9284d27e-ao-O.svg">

```

**Comment by langfield** [comment]
I have reproduced this error in a test, and it does indeed fail reproducibly on Windows (not that I had any doubt, your bug reports are always impeccable).

```python
        """If there are e.g. asterisks in a `guid`, do we still write the note file successfully?"""
        ORIGINAL: SampleCollection = get_test_collection("original")
        col = Collection(ORIGINAL.col_file)
        timestamp_ns: int = time.time_ns()
        new_nids: Iterator[int] = itertools.count(int(timestamp_ns / 1e6))

        for nid, guid, mod, mid in col.db.execute("select id, guid, mod, mid from notes"):
            logger.debug(f"{nid = }")
            logger.debug(f"{mod = }")
            logger.debug(f"{mid = }")

        nid = next(new_nids)
        mod = next(new_nids)
        mid = 1645010146011
        guid = r"QM6kTt.Nt*"
        decknote = DeckNote(
            title="title",
            guid=guid,
            deck="Default",
            model="Basic",
            tags=[],
            fields={"Front": "", "Back": "b"},
        )
        note: Note = add_db_note(
            col,
            nid,
            guid,
            mid,
            mod=int(timestamp_ns // 1e9),
            usn=-1,
            tags=decknote.tags,
            fields=list(decknote.fields.values()),
            sfld="",
            csum=0,
            flags=0,
            data="",
        )
        notetype: Notetype = parse_notetype_dict(note.note_type())

        runner = CliRunner()
        with runner.isolated_filesystem(temp_dir=tmp_path):
            targetdir: ExtantDir = F.mkdir(F.test(Path("collection")))
            colnote = ColNote(
                n=note,
                new=True,
                deck="Default",
                title="None",
                markdown=False,
                notetype=notetype,
                sortf_text="",
            )
            note_path: NoFile = get_note_path(colnote, targetdir)
            payload: str = "payload"
>           note_path: ExtantFile = F.write(note_path, payload)

tests\test_ki.py:1798:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
<@beartype(ki.functional.write) at 0x223c22e0e50>:52: in write
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = NoFile('collection/QM6kTt.Nt*.md'), text = 'payload'

    @beartype
    def write(path: Union[ExtantFile, NoFile], text: str) -> ExtantFile:
        """Write text to a file."""
>       with open(path, "w+", encoding="UTF-8") as f:
E       OSError: [Errno 22] Invalid argument: 'collection\\QM6kTt.Nt*.md'

ki\functional.py:164: OSError
```

**Comment by langfield** [comment]
Plan is to take the `blake2` hash of the note payload and use that as the filename instead. We'll also implement this `TODO`:
```python
# TODO: This should use other fields when there is not enough content in the
# first field to get a unique filename, if they exist. Note that we must still
# treat the case where all fields are images!
@beartype
def get_note_path(colnote: ColNote, payload: str, deck_dir: ExtantDir, card_name: str = "") -> NoFile:
    """Get note path from sort field text."""
```
and prefix the filenames for notes with empty contents with their notetype and creation date. This should dramatically reduce the number of notes that require a warning analogous to `WARNING  | ki:get_note_path:853 - Slug for 'QM6kTt.Nt*' is empty. Using guid as filename`, and also make the autogenerated filenames more meaningful when we *do* run into those remaining cases.

**Comment by langfield** [comment]
Merged! Please reopen or create a new issue if you find the problem persists!

**Comment by pwintz** [comment]
Great! Cloning works now and does not produce warnings anymore. I'll start testing out Ki in ernest when I get a chance.

**Comment by langfield** [comment]
@pwintz Fantastic!
