### ISSUE TITLE
Should you be able to modify `guid`s within a repository?

### ISSUE THREAD

**Issue by langfield** [langfield/ki#88]
Currently this possibly raises an error, although we must fix the `guid` filename issue before it can be settled definitively. This might work once #87 is fixed.

```python
( ●    ) Initializing stage repository...
(  ●   ) Initializing stage repository...
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Notes:   0%|                                              | 0/1 [00:00<?, ?it/s]

  0%|                                                     | 0/1 [00:00<?, ?it/s]
HTML:   0%|                                               | 0/1 [00:00<?, ?it/s]

  0%|                                                     | 0/1 [00:00<?, ?it/s]
Media:   0%|                                              | 0/1 [00:00<?, ?it/s]

  0%|                                                     | 0/2 [00:00<?, ?it/s]
Decks:   0%|                                              | 0/2 [00:00<?, ?it/s]

2022-09-10 09:59:16.690 | WARNING  | ki:get_note_path:853 - Slug for 'kY>vpL:(`j' is empty. Using guid as filename

Warnings suppressed: 0 (show with '--verbose')
( ●    ) Initializing repository and committing contents...
(  ●   ) Initializing repository and committing contents...
( ●    ) Copying blobs at HEAD='3ef418e3235f367bf8c93b996df5a6e65717ef18'  (...)
(  ●   ) Copying blobs at HEAD='3ef418e3235f367bf8c93b996df5a6e65717ef18'  (...)
( ●    ) Flattening stage repository submodules in '/tmp/tmpvu4u5i6n/ki-re (...)
(  ●   ) Flattening stage repository submodules in '/tmp/tmpvu4u5i6n/ki-re (...)
( ●    ) Committing stage repository contents in '/tmp/tmpvu4u5i6n/ki-remo (...)
(  ●   ) Committing stage repository contents in '/tmp/tmpvu4u5i6n/ki-remo (...)
( ●    ) Checking out repo '/tmp/tmpvu4u5i6n/ki-remote/d1a6c1ed7c61b67ba5c (...)
(  ●   ) Checking out repo '/tmp/tmpvu4u5i6n/ki-remote/d1a6c1ed7c61b67ba5c (...)
( ●    ) Diffing 'e5402c62dce11afa85b54371ca165c0b5c286fec' ~ 'ee600a71da5 (...)
(  ●   ) Diffing 'e5402c62dce11afa85b54371ca165c0b5c286fec' ~ 'ee600a71da5 (...)
ERROR:git.cmd:Pumping 'stdout' of cmd(['git', 'diff-tree', 'e5402c62dce11afa85b54371ca165c0b5c286fec', 'ee600a71da5c5dbc9eea394f618c8091ccac337d', '-r', '--abbrev=40', '--full-index', '-M', '--raw', '-z', '--no-color']) failed due to:
ValueError('not enough values to unpack (expected 5, got 1)')

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/conda/envs/anki/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/user/conda/envs/anki/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/conda/envs/anki/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree e5402c62dce11afa85b54371ca165c0b5c286fec ee600a71da5c5dbc9eea394f618c8091ccac337d -r --abbrev=40 --full-index -M --raw -z --no-color

0it [00:00, ?it/s]
GitChangeType.ADDED: : 0it [00:00, ?it/s]

0it [00:00, ?it/s]
GitChangeType.DELETED: : 0it [00:00, ?it/s]

0it [00:00, ?it/s]
GitChangeType.RENAMED: : 0it [00:00, ?it/s]

0it [00:00, ?it/s]
GitChangeType.MODIFIED: : 0it [00:00, ?it/s]

0it [00:00, ?it/s]
GitChangeType.TYPECHANGED: : 0it [00:00, ?it/s]

  0%|                                                     | 0/2 [00:00<?, ?it/s]
Models:   0%|                                             | 0/2 [00:00<?, ?it/s]

Diff target file not found: 'Default/kY>vpL'

Unexpected: this sometimes happens when a git repository is copied
into a subdirectory of a ki repository, and then added with 'git add'
instead of being added as a git submodule with 'git submodule add'.
If git displayed a warning on a recent 'git add' command, refer to
the hints within that warning.

Otherwise, this may indicate a bug in ki.  The caller prevents this
warning from being instantiated unless the git change type is one of
'ADDED', 'MODIFIED', or 'RENAMED'. In all cases, the file being
diffed should be extant in the target commit of the repository.
However, we return a 'Warning' instead of an 'Exception' in order to
avoid interrupting the execution of a 'push()' call where it is not
strictly necessary.
ki push: up to date.
```

**Comment by langfield** [comment]
Let's say no, because if we have users manually messing with `guid`s, then they're probably not globally unique anymore. That's bad. Also this seems like feature creep.
